/* Länderprofile für die Detailseite (land.html): Beitrittsjahr sowie
   Verbindung zur EU, Beitritt und Schwierigkeiten in DE / EN / RU / ZH. */

window.EU_COUNTRY_INFO = {
  DE: { year: 1958,
    de: { rel: "Deutschland ist Gründungsmitglied und mit rund 83 Millionen Einwohnern das bevölkerungsreichste Land der EU. Als größte Volkswirtschaft gilt es zusammen mit Frankreich als Motor der europäischen Integration.",
      join: "Nach dem Zweiten Weltkrieg gründete die Bundesrepublik 1951 die Montanunion und 1957 die EWG mit. Ziel war, das frühere Kriegsland fest in ein gemeinsames Europa einzubinden.",
      diff: "Bis 1990 gehörte nur Westdeutschland dazu; der Osten kam erst mit der Wiedervereinigung hinzu. Bis heute zahlt Deutschland am meisten in den EU-Haushalt ein, was immer wieder für Diskussionen sorgt." },
    en: { rel: "Germany is a founding member and, with around 83 million people, the EU's most populous country. As its largest economy it is considered, together with France, the engine of European integration.",
      join: "After the Second World War West Germany co-founded the Coal and Steel Community in 1951 and the EEC in 1957. The aim was to bind the former warring nation firmly into a shared Europe.",
      diff: "Until 1990 only West Germany was a member; the East joined only through reunification. Germany still pays the most into the EU budget, which repeatedly sparks debate." },
    ru: { rel: "Германия — страна-основатель и с населением около 83 млн человек самая крупная по числу жителей в ЕС. Как крупнейшая экономика она вместе с Францией считается мотором европейской интеграции.",
      join: "После Второй мировой войны ФРГ в 1951 году участвовала в создании Объединения угля и стали, а в 1957-м — ЕЭС. Цель была прочно связать бывшую воюющую страну с общей Европой.",
      diff: "До 1990 года в союз входила только Западная Германия; восток присоединился лишь после объединения страны. Германия по-прежнему вносит больше всех в бюджет ЕС, что регулярно вызывает споры." },
    zh: { rel: "德国是创始成员国，约8300万人口使其成为欧盟人口最多的国家。作为最大经济体，它与法国一起被视为欧洲一体化的引擎。",
      join: "二战后，西德于1951年参与创立煤钢共同体，1957年参与创立欧洲经济共同体。目的是把这个昔日的交战国牢牢地融入共同的欧洲。",
      diff: "1990年前只有西德是成员；东部通过两德统一才加入。德国至今向欧盟预算缴纳最多，这不断引发争论。" } },

  FR: { year: 1958,
    de: { rel: "Frankreich ist Gründungsmitglied und gilt neben Deutschland als treibende Kraft der EU. Die entscheidenden ersten Ideen zur Einigung Europas kamen von französischen Politikern.",
      join: "Außenminister Robert Schuman schlug 1950 vor, Kohle und Stahl gemeinsam zu verwalten, um einen Krieg mit Deutschland unmöglich zu machen. Daraus entstand 1957 die EWG.",
      diff: "1954 lehnte das französische Parlament eine geplante Europäische Verteidigungsgemeinschaft ab. 2005 stimmten die Franzosen zudem gegen die geplante EU-Verfassung." },
    en: { rel: "France is a founding member and, alongside Germany, is seen as a driving force of the EU. The decisive early ideas for uniting Europe came from French politicians.",
      join: "In 1950 Foreign Minister Robert Schuman proposed managing coal and steel jointly to make war with Germany impossible. This led to the EEC in 1957.",
      diff: "In 1954 the French parliament rejected a planned European Defence Community. In 2005 French voters also rejected the proposed EU constitution." },
    ru: { rel: "Франция — страна-основатель и наряду с Германией считается движущей силой ЕС. Решающие первые идеи объединения Европы исходили от французских политиков.",
      join: "В 1950 году министр иностранных дел Робер Шуман предложил совместно управлять углём и сталью, чтобы сделать войну с Германией невозможной. Так в 1957 году возникло ЕЭС.",
      diff: "В 1954 году французский парламент отклонил проект Европейского оборонительного сообщества. А в 2005 году французы проголосовали против предложенной конституции ЕС." },
    zh: { rel: "法国是创始成员国，与德国一同被视为欧盟的推动力量。统一欧洲最初的关键构想来自法国政治家。",
      join: "1950年，外长罗贝尔·舒曼提议共同管理煤炭与钢铁，以使与德国的战争无法发生。由此在1957年产生了欧洲经济共同体。",
      diff: "1954年，法国议会否决了拟议中的欧洲防务共同体。2005年，法国选民又否决了拟议的欧盟宪法。" } },

  IT: { year: 1958,
    de: { rel: "Italien ist Gründungsmitglied; die berühmten Römischen Verträge wurden 1957 in Rom unterzeichnet. Das Land war von Anfang an stark proeuropäisch.",
      join: "Italien schloss sich 1951 der Montanunion und 1957 der EWG an. Man erhoffte sich wirtschaftlichen Aufschwung und dauerhaften Frieden nach dem Krieg.",
      diff: "Die hohe Staatsverschuldung brachte Italien wiederholt in Konflikt mit den Regeln der Euro-Zone. Häufige Regierungswechsel erschwerten zudem eine stabile Europapolitik." },
    en: { rel: "Italy is a founding member; the famous Treaties of Rome were signed there in 1957. The country was strongly pro-European from the start.",
      join: "Italy joined the Coal and Steel Community in 1951 and the EEC in 1957. It hoped for economic growth and lasting peace after the war.",
      diff: "Its high national debt has repeatedly brought Italy into conflict with euro-zone rules. Frequent changes of government have also made a stable European policy difficult." },
    ru: { rel: "Италия — страна-основатель; знаменитые Римские договоры были подписаны в Риме в 1957 году. С самого начала страна была настроена крайне проевропейски.",
      join: "Италия присоединилась к Объединению угля и стали в 1951 году и к ЕЭС в 1957-м. Она надеялась на экономический подъём и прочный мир после войны.",
      diff: "Высокий государственный долг не раз приводил Италию к конфликту с правилами еврозоны. Частая смена правительств также затрудняла стабильную европейскую политику." },
    zh: { rel: "意大利是创始成员国；著名的《罗马条约》于1957年在罗马签署。该国从一开始就强烈支持欧洲一体化。",
      join: "意大利于1951年加入煤钢共同体，1957年加入欧洲经济共同体。它期望战后实现经济增长与持久和平。",
      diff: "高额的国家债务多次使意大利与欧元区规则发生冲突。频繁更换政府也使稳定的欧洲政策变得困难。" } },

  ES: { year: 1986,
    de: { rel: "Spanien trat 1986 bei, kurz nachdem die Diktatur Francos geendet hatte. Die EU-Mitgliedschaft festigte die junge Demokratie des Landes.",
      join: "Nach Francos Tod 1975 beantragte Spanien 1977 die Aufnahme und wurde 1986 zusammen mit Portugal Mitglied. Der Beitritt galt als Rückkehr nach Europa.",
      diff: "Die Verhandlungen zogen sich wegen Landwirtschaft und Fischerei lange hin. Später traf die Finanzkrise das Land hart: 2012 brauchte Spanien Hilfe für seine Banken." },
    en: { rel: "Spain joined in 1986, shortly after Franco's dictatorship had ended. EU membership helped consolidate the country's young democracy.",
      join: "After Franco's death in 1975, Spain applied in 1977 and became a member in 1986 together with Portugal. The accession was seen as a return to Europe.",
      diff: "Negotiations dragged on for years over agriculture and fisheries. Later the financial crisis hit hard: in 2012 Spain needed help to rescue its banks." },
    ru: { rel: "Испания вступила в 1986 году, вскоре после падения диктатуры Франко. Членство в ЕС укрепило молодую демократию страны.",
      join: "После смерти Франко в 1975 году Испания подала заявку в 1977-м и стала членом в 1986 году вместе с Португалией. Вступление воспринималось как возвращение в Европу.",
      diff: "Переговоры затянулись из-за вопросов сельского хозяйства и рыболовства. Позже финансовый кризис сильно ударил по стране: в 2012 году Испании понадобилась помощь для банков." },
    zh: { rel: "西班牙于1986年加入，此时佛朗哥独裁刚刚结束不久。加入欧盟帮助巩固了这个国家年轻的民主。",
      join: "1975年佛朗哥去世后，西班牙于1977年提出申请，并在1986年与葡萄牙一同成为成员。此次加入被视为“重返欧洲”。",
      diff: "谈判因农业和渔业问题拖延多年。后来金融危机重创该国：2012年西班牙需要援助来拯救其银行。" } },

  PL: { year: 2004,
    de: { rel: "Polen trat 2004 bei und ist das größte der damals aufgenommenen Länder. Es zählt zu den größten Empfängern von EU-Fördergeldern.",
      join: "Nach dem Ende des Kommunismus 1989 strebte Polen nach Westen. In einer Volksabstimmung 2003 stimmte eine klare Mehrheit für den Beitritt.",
      diff: "In den letzten Jahren gab es scharfe Konflikte mit Brüssel über die Unabhängigkeit der Justiz und die Rechtsstaatlichkeit. Zeitweise wurden deshalb EU-Gelder zurückgehalten." },
    en: { rel: "Poland joined in 2004 and is the largest of the countries admitted then. It is among the biggest recipients of EU funding.",
      join: "After the end of communism in 1989 Poland turned westward. In a 2003 referendum a clear majority voted to join.",
      diff: "In recent years there have been sharp conflicts with Brussels over the independence of the judiciary and the rule of law. At times EU funds were withheld as a result." },
    ru: { rel: "Польша вступила в 2004 году и является крупнейшей из принятых тогда стран. Она в числе крупнейших получателей средств ЕС.",
      join: "После краха коммунизма в 1989 году Польша устремилась на Запад. На референдуме 2003 года явное большинство проголосовало за вступление.",
      diff: "В последние годы возникли острые конфликты с Брюсселем из-за независимости судебной системы и верховенства права. Временами из-за этого приостанавливалось финансирование ЕС." },
    zh: { rel: "波兰于2004年加入，是当时接纳国家中最大的一个。它是欧盟资金最大的受益者之一。",
      join: "1989年共产主义结束后，波兰转向西方。在2003年的全民公投中，明显多数投票赞成加入。",
      diff: "近年来，波兰在司法独立和法治问题上与布鲁塞尔发生激烈冲突。为此欧盟一度暂扣拨款。" } },

  RO: { year: 2007,
    de: { rel: "Rumänien trat 2007 gemeinsam mit Bulgarien bei. Damit rückte die EU bis an das Schwarze Meer heran.",
      join: "Nach dem Sturz des Diktators Ceaușescu 1989 begann ein langer Reformweg; den Antrag stellte das Land 1995.",
      diff: "Wegen Korruption und Mängeln im Justizwesen wurde der Beitritt bis 2007 verschoben und danach besonders überwacht. Auch der volle Beitritt zum Schengen-Raum ließ lange auf sich warten." },
    en: { rel: "Romania joined in 2007 together with Bulgaria, extending the EU to the Black Sea.",
      join: "After the fall of the dictator Ceaușescu in 1989 a long path of reform began; the country applied in 1995.",
      diff: "Because of corruption and shortcomings in the justice system, accession was delayed until 2007 and closely monitored afterwards. Full membership of the Schengen Area also took a long time." },
    ru: { rel: "Румыния вступила в 2007 году вместе с Болгарией, и ЕС вплотную подошёл к Чёрному морю.",
      join: "После свержения диктатора Чаушеску в 1989 году начался долгий путь реформ; заявку страна подала в 1995 году.",
      diff: "Из-за коррупции и недостатков судебной системы вступление отложили до 2007 года и затем особо контролировали. Полноценное присоединение к Шенгену также заставило себя долго ждать." },
    zh: { rel: "罗马尼亚于2007年与保加利亚一同加入，使欧盟延伸至黑海。",
      join: "1989年独裁者齐奥塞斯库倒台后，开始了漫长的改革之路；该国于1995年提出申请。",
      diff: "由于腐败和司法制度的缺陷，加入被推迟到2007年，此后受到特别监督。完全加入申根区也等待了很久。" } },

  NL: { year: 1958,
    de: { rel: "Die Niederlande sind Gründungsmitglied und ein traditionell handelsorientiertes Land. In Maastricht wurde 1992 der Vertrag zur Gründung der EU unterzeichnet.",
      join: "Als kleines Handelsland setzte es früh auf europäische Zusammenarbeit und bildete mit Belgien und Luxemburg die Benelux-Union. 1957 gehörte es zu den Gründern der EWG.",
      diff: "2005 lehnten die Niederländer in einer Volksabstimmung die EU-Verfassung ab. Das Land fordert häufig einen sparsamen EU-Haushalt." },
    en: { rel: "The Netherlands is a founding member and a traditionally trade-oriented country. The treaty founding the EU was signed in Maastricht in 1992.",
      join: "As a small trading nation it embraced European cooperation early and formed the Benelux union with Belgium and Luxembourg. In 1957 it was among the founders of the EEC.",
      diff: "In 2005 Dutch voters rejected the EU constitution in a referendum. The country often calls for a thrifty EU budget." },
    ru: { rel: "Нидерланды — страна-основатель и традиционно ориентированная на торговлю. В Маастрихте в 1992 году был подписан договор об учреждении ЕС.",
      join: "Как небольшая торговая страна она рано сделала ставку на европейское сотрудничество и вместе с Бельгией и Люксембургом образовала Бенилюкс. В 1957 году она была среди основателей ЕЭС.",
      diff: "В 2005 году голландцы на референдуме отклонили конституцию ЕС. Страна часто требует экономного бюджета ЕС." },
    zh: { rel: "荷兰是创始成员国，是传统上以贸易为导向的国家。创立欧盟的条约于1992年在马斯特里赫特签署。",
      join: "作为一个小型贸易国家，它很早就致力于欧洲合作，并与比利时、卢森堡组成比荷卢联盟。1957年它是欧洲经济共同体的创始国之一。",
      diff: "2005年，荷兰选民在公投中否决了欧盟宪法。该国经常呼吁节俭的欧盟预算。" } },

  BE: { year: 1958,
    de: { rel: "Belgien ist Gründungsmitglied, und Brüssel ist heute der wichtigste Sitz der EU-Institutionen. Das Land wird oft als „Hauptstadt Europas“ bezeichnet.",
      join: "Schon vor der EWG bildete Belgien mit den Niederlanden und Luxemburg die Benelux-Zollunion. 1957 gehörte es zu den sechs Gründerstaaten.",
      diff: "Innenpolitisch ist Belgien durch die Spannungen zwischen Flamen und Wallonen geprägt. Als kleines Land muss es seine Interessen geschickt in der EU vertreten." },
    en: { rel: "Belgium is a founding member, and Brussels is today the main seat of the EU institutions. The country is often called the \"capital of Europe\".",
      join: "Even before the EEC, Belgium formed the Benelux customs union with the Netherlands and Luxembourg. In 1957 it was one of the six founding states.",
      diff: "Domestically Belgium is marked by tensions between Flemish and Walloon communities. As a small country it must represent its interests skilfully within the EU." },
    ru: { rel: "Бельгия — страна-основатель, а Брюссель сегодня главное место расположения институтов ЕС. Страну часто называют «столицей Европы».",
      join: "Ещё до ЕЭС Бельгия образовала таможенный союз Бенилюкс с Нидерландами и Люксембургом. В 1957 году она была одним из шести государств-основателей.",
      diff: "Во внутренней политике Бельгия отмечена напряжённостью между фламандцами и валлонами. Как небольшая страна ей приходится умело отстаивать свои интересы в ЕС." },
    zh: { rel: "比利时是创始成员国，布鲁塞尔如今是欧盟机构的主要所在地。该国常被称为“欧洲之都”。",
      join: "早在欧洲经济共同体之前，比利时就与荷兰、卢森堡组成了比荷卢关税同盟。1957年它是六个创始国之一。",
      diff: "在国内，比利时受到弗拉芒人与瓦隆人之间紧张关系的影响。作为小国，它必须在欧盟中巧妙地维护自身利益。" } },

  CZ: { year: 2004,
    de: { rel: "Tschechien trat 2004 bei, rund 15 Jahre nach der friedlichen „Samtenen Revolution“. Es nutzt bis heute die eigene Krone statt des Euro.",
      join: "1993 entstand Tschechien durch die Teilung der Tschechoslowakei. In einer Volksabstimmung 2003 stimmten die Bürger für den Beitritt.",
      diff: "Der eurokritische Präsident Václav Klaus verzögerte die Unterzeichnung des Vertrags von Lissabon. Auch die Einführung des Euro wurde immer wieder verschoben." },
    en: { rel: "Czechia joined in 2004, about 15 years after the peaceful \"Velvet Revolution\". It still uses its own koruna instead of the euro.",
      join: "Czechia came into being in 1993 through the split of Czechoslovakia. In a 2003 referendum citizens voted to join.",
      diff: "The eurosceptic president Václav Klaus delayed signing the Treaty of Lisbon. Adoption of the euro has also been repeatedly postponed." },
    ru: { rel: "Чехия вступила в 2004 году, примерно через 15 лет после мирной «бархатной революции». Она до сих пор использует собственную крону вместо евро.",
      join: "Чехия возникла в 1993 году в результате разделения Чехословакии. На референдуме 2003 года граждане проголосовали за вступление.",
      diff: "Евроскептически настроенный президент Вацлав Клаус задержал подписание Лиссабонского договора. Введение евро также неоднократно откладывалось." },
    zh: { rel: "捷克于2004年加入，约在和平的“天鹅绒革命”15年后。它至今仍使用本国克朗而非欧元。",
      join: "捷克于1993年因捷克斯洛伐克分裂而诞生。在2003年的公投中，公民投票赞成加入。",
      diff: "持怀疑欧盟态度的总统瓦茨拉夫·克劳斯拖延了《里斯本条约》的签署。采用欧元也一再被推迟。" } },

  SE: { year: 1995,
    de: { rel: "Schweden trat 1995 bei, behielt aber die eigene Krone. Das Land legt großen Wert auf Umweltschutz und Transparenz.",
      join: "Erst nach dem Ende des Kalten Krieges gab Schweden seine strikte Neutralität auf. 1994 stimmten die Bürger knapp für den Beitritt.",
      diff: "2003 lehnten die Schweden in einer Volksabstimmung die Einführung des Euro ab. Bis heute ist die Skepsis gegenüber einer engeren Union verbreitet." },
    en: { rel: "Sweden joined in 1995 but kept its own krona. The country places great emphasis on environmental protection and transparency.",
      join: "Only after the end of the Cold War did Sweden give up its strict neutrality. In 1994 citizens narrowly voted to join.",
      diff: "In 2003 Swedes rejected adopting the euro in a referendum. Scepticism towards a closer union remains widespread today." },
    ru: { rel: "Швеция вступила в 1995 году, но сохранила собственную крону. Страна придаёт большое значение защите окружающей среды и прозрачности.",
      join: "Лишь после окончания холодной войны Швеция отказалась от строгого нейтралитета. В 1994 году граждане с небольшим перевесом проголосовали за вступление.",
      diff: "В 2003 году шведы на референдуме отклонили введение евро. Скептицизм по отношению к более тесному союзу распространён и сегодня." },
    zh: { rel: "瑞典于1995年加入，但保留了本国克朗。该国高度重视环境保护与透明度。",
      join: "直到冷战结束后，瑞典才放弃其严格的中立立场。1994年公民以微弱多数投票赞成加入。",
      diff: "2003年，瑞典人在公投中否决了采用欧元。至今对更紧密联盟的怀疑仍很普遍。" } },

  PT: { year: 1986,
    de: { rel: "Portugal trat 1986 zusammen mit Spanien bei, nachdem eine lange Diktatur geendet hatte. Die Mitgliedschaft brachte dem Land Modernisierung und Stabilität.",
      join: "Nach der friedlichen „Nelkenrevolution“ 1974 wandte sich Portugal Europa zu und beantragte 1977 die Aufnahme.",
      diff: "Der Weg zur Mitgliedschaft war wirtschaftlich schwierig. In der Schuldenkrise musste Portugal 2011 mit einem Rettungspaket der EU gestützt werden." },
    en: { rel: "Portugal joined in 1986 together with Spain after a long dictatorship had ended. Membership brought the country modernisation and stability.",
      join: "After the peaceful \"Carnation Revolution\" of 1974, Portugal turned to Europe and applied for membership in 1977.",
      diff: "The road to membership was economically difficult. During the debt crisis Portugal had to be supported by an EU bailout in 2011." },
    ru: { rel: "Португалия вступила в 1986 году вместе с Испанией, после того как закончилась долгая диктатура. Членство принесло стране модернизацию и стабильность.",
      join: "После мирной «революции гвоздик» 1974 года Португалия повернулась к Европе и подала заявку в 1977 году.",
      diff: "Путь к членству был экономически трудным. Во время долгового кризиса Португалии в 2011 году потребовалась программа помощи ЕС." },
    zh: { rel: "葡萄牙于1986年在长期独裁结束后与西班牙一同加入。成员资格为该国带来了现代化与稳定。",
      join: "1974年和平的“康乃馨革命”之后，葡萄牙转向欧洲，并于1977年申请加入。",
      diff: "通往成员资格的道路在经济上十分艰难。在债务危机期间，葡萄牙于2011年不得不接受欧盟救助。" } },

  GR: { year: 1981,
    de: { rel: "Griechenland trat 1981 als zehntes Mitglied bei und war das erste Land der südlichen Erweiterung. Das Land gilt als Wiege der europäischen Kultur.",
      join: "Nach dem Ende der Militärdiktatur 1974 wandte sich Griechenland rasch der Gemeinschaft zu und wurde 1981 aufgenommen.",
      diff: "Ab 2010 geriet das Land in eine schwere Schuldenkrise. Nur mit mehreren Rettungspaketen und harten Sparauflagen konnte ein Ausscheiden aus dem Euro verhindert werden." },
    en: { rel: "Greece joined in 1981 as the tenth member and was the first country of the southern enlargement. It is regarded as the cradle of European culture.",
      join: "After the end of the military dictatorship in 1974, Greece quickly turned to the Community and was admitted in 1981.",
      diff: "From 2010 the country fell into a severe debt crisis. Only several bailouts and harsh austerity measures prevented it from leaving the euro." },
    ru: { rel: "Греция вступила в 1981 году как десятый член и стала первой страной южного расширения. Её считают колыбелью европейской культуры.",
      join: "После падения военной диктатуры в 1974 году Греция быстро повернулась к Сообществу и была принята в 1981 году.",
      diff: "С 2010 года страна оказалась в тяжёлом долговом кризисе. Только несколько пакетов помощи и жёсткая экономия предотвратили выход из зоны евро." },
    zh: { rel: "希腊于1981年作为第十个成员国加入，是南方扩盟的第一个国家。它被视为欧洲文化的摇篮。",
      join: "1974年军事独裁结束后，希腊迅速转向共同体，并于1981年获接纳。",
      diff: "从2010年起，该国陷入严重的债务危机。只有依靠多轮救助和严厉的紧缩措施，才避免了退出欧元区。" } },

  HU: { year: 2004,
    de: { rel: "Ungarn trat 2004 bei und liegt im Herzen Mitteleuropas. Es war eines der ersten Länder, das die Grenze zum Westen öffnete.",
      join: "Nach dem Ende des Kommunismus strebte Ungarn nach Westintegration. 2003 stimmten die Bürger in einer Volksabstimmung für den Beitritt.",
      diff: "In den letzten Jahren gab es Streit mit der EU über Rechtsstaatlichkeit, Medienfreiheit und die Unabhängigkeit der Gerichte. Deshalb wurden zeitweise EU-Gelder eingefroren." },
    en: { rel: "Hungary joined in 2004 and lies in the heart of Central Europe. It was one of the first countries to open its border to the West.",
      join: "After the end of communism Hungary sought integration with the West. In 2003 citizens voted to join in a referendum.",
      diff: "In recent years there have been disputes with the EU over the rule of law, media freedom and the independence of the courts. As a result EU funds were temporarily frozen." },
    ru: { rel: "Венгрия вступила в 2004 году и расположена в сердце Центральной Европы. Она была одной из первых стран, открывших границу на Запад.",
      join: "После краха коммунизма Венгрия стремилась к интеграции с Западом. В 2003 году граждане на референдуме проголосовали за вступление.",
      diff: "В последние годы возникли споры с ЕС о верховенстве права, свободе СМИ и независимости судов. Из-за этого средства ЕС временно замораживались." },
    zh: { rel: "匈牙利于2004年加入，位于中欧的中心。它是最早向西方开放边界的国家之一。",
      join: "共产主义结束后，匈牙利寻求与西方一体化。2003年公民在公投中投票赞成加入。",
      diff: "近年来，匈牙利在法治、新闻自由和司法独立方面与欧盟发生争议。为此欧盟一度冻结拨款。" } },

  AT: { year: 1995,
    de: { rel: "Österreich trat 1995 bei und liegt zentral in Europa. Als kleineres Land setzt es stark auf den gemeinsamen Markt.",
      join: "Nach dem Ende des Kalten Krieges war der Beitritt möglich; 1994 stimmten zwei Drittel der Österreicher dafür.",
      diff: "Wegen seiner traditionellen Neutralität war der Weg lange umstritten. Als 2000 eine rechte Partei in die Regierung kam, verhängten andere EU-Staaten zeitweise Sanktionen." },
    en: { rel: "Austria joined in 1995 and lies centrally in Europe. As a smaller country it relies heavily on the single market.",
      join: "Accession became possible after the end of the Cold War; in 1994 two-thirds of Austrians voted in favour.",
      diff: "Because of its traditional neutrality, the path was long contested. When a right-wing party entered government in 2000, other EU states imposed temporary sanctions." },
    ru: { rel: "Австрия вступила в 1995 году и расположена в центре Европы. Как небольшая страна она сильно опирается на общий рынок.",
      join: "Вступление стало возможным после окончания холодной войны; в 1994 году две трети австрийцев проголосовали за.",
      diff: "Из-за традиционного нейтралитета путь долго был спорным. Когда в 2000 году в правительство вошла правая партия, другие страны ЕС ввели временные санкции." },
    zh: { rel: "奥地利于1995年加入，位于欧洲中心。作为较小的国家，它高度依赖统一市场。",
      join: "冷战结束后加入成为可能；1994年三分之二的奥地利人投票赞成。",
      diff: "由于其传统的中立立场，这条道路长期存在争议。2000年一个右翼政党进入政府时，其他欧盟国家一度实施制裁。" } },

  BG: { year: 2007,
    de: { rel: "Bulgarien trat 2007 gemeinsam mit Rumänien bei. Es ist eines der jüngeren und wirtschaftlich schwächeren Mitglieder.",
      join: "Nach dem Ende des Kommunismus 1989 durchlief das Land eine lange Phase von Reformen, um die Aufnahmekriterien zu erfüllen.",
      diff: "Wegen Korruption und organisierter Kriminalität stand Bulgarien lange unter besonderer Beobachtung. Der Beitritt zum Schengen-Raum und zum Euro verzögerte sich dadurch." },
    en: { rel: "Bulgaria joined in 2007 together with Romania. It is one of the younger and economically weaker members.",
      join: "After the end of communism in 1989 the country went through a long phase of reforms to meet the accession criteria.",
      diff: "Because of corruption and organised crime, Bulgaria was long kept under special monitoring. Joining the Schengen Area and the euro was delayed as a result." },
    ru: { rel: "Болгария вступила в 2007 году вместе с Румынией. Это один из более молодых и экономически более слабых членов.",
      join: "После краха коммунизма в 1989 году страна прошла долгий этап реформ, чтобы соответствовать критериям вступления.",
      diff: "Из-за коррупции и организованной преступности Болгария долго находилась под особым наблюдением. Из-за этого затянулось присоединение к Шенгену и евро." },
    zh: { rel: "保加利亚于2007年与罗马尼亚一同加入。它是较年轻、经济较弱的成员之一。",
      join: "1989年共产主义结束后，该国经历了漫长的改革阶段，以达到加入标准。",
      diff: "由于腐败和有组织犯罪，保加利亚长期处于特别监督之下。加入申根区和欧元也因此被推迟。" } },

  DK: { year: 1973,
    de: { rel: "Dänemark trat 1973 zusammen mit Großbritannien und Irland bei. Es behielt jedoch die eigene Krone und mehrere Sonderregelungen.",
      join: "In einer Volksabstimmung 1972 sprachen sich die Dänen klar für den Beitritt aus, vor allem aus wirtschaftlichen Gründen.",
      diff: "1992 lehnten die Dänen zunächst den Vertrag von Maastricht ab. Erst mit Ausnahmen etwa beim Euro und der Verteidigung stimmten sie später zu." },
    en: { rel: "Denmark joined in 1973 together with the United Kingdom and Ireland. It kept its own krone and several special arrangements, however.",
      join: "In a 1972 referendum Danes clearly voted to join, mainly for economic reasons.",
      diff: "In 1992 Danes at first rejected the Treaty of Maastricht. Only with opt-outs, for example on the euro and defence, did they later agree." },
    ru: { rel: "Дания вступила в 1973 году вместе с Великобританией и Ирландией. Однако она сохранила собственную крону и несколько особых условий.",
      join: "На референдуме 1972 года датчане чётко высказались за вступление, прежде всего по экономическим причинам.",
      diff: "В 1992 году датчане сначала отклонили Маастрихтский договор. Лишь получив исключения, например по евро и обороне, они позже согласились." },
    zh: { rel: "丹麦于1973年与英国、爱尔兰一同加入。但它保留了本国克朗和若干特别安排。",
      join: "在1972年的公投中，丹麦人明确投票赞成加入，主要出于经济原因。",
      diff: "1992年，丹麦人起初否决了《马斯特里赫特条约》。后来只有在获得欧元和防务等方面的豁免后才同意。" } },

  FI: { year: 1995,
    de: { rel: "Finnland trat 1995 bei und ist das einzige nordische EU-Land, das den Euro eingeführt hat. Es gilt als besonders gut integriert.",
      join: "Nach dem Ende des Kalten Krieges gab Finnland seine Zurückhaltung auf; 1994 stimmten die Bürger für den Beitritt.",
      diff: "Wegen der langen Grenze zu Russland und einer Tradition der Neutralität war die Annäherung an den Westen ein sensibler Schritt." },
    en: { rel: "Finland joined in 1995 and is the only Nordic EU country to have adopted the euro. It is considered especially well integrated.",
      join: "After the end of the Cold War Finland gave up its restraint; in 1994 citizens voted to join.",
      diff: "Because of its long border with Russia and a tradition of neutrality, moving closer to the West was a sensitive step." },
    ru: { rel: "Финляндия вступила в 1995 году и является единственной северной страной ЕС, которая ввела евро. Она считается особенно хорошо интегрированной.",
      join: "После окончания холодной войны Финляндия отказалась от сдержанности; в 1994 году граждане проголосовали за вступление.",
      diff: "Из-за протяжённой границы с Россией и традиции нейтралитета сближение с Западом было деликатным шагом." },
    zh: { rel: "芬兰于1995年加入，是唯一采用欧元的北欧欧盟国家。它被认为融合得特别好。",
      join: "冷战结束后，芬兰放弃了克制；1994年公民投票赞成加入。",
      diff: "由于与俄罗斯有漫长的边界以及中立传统，向西方靠拢是一个敏感的步骤。" } },

  SK: { year: 2004,
    de: { rel: "Die Slowakei trat 2004 bei und führte 2009 den Euro ein. Sie gilt heute als solide in die EU integriert.",
      join: "1993 entstand die Slowakei durch die friedliche Teilung der Tschechoslowakei. 2003 stimmten die Bürger für den Beitritt.",
      diff: "In den 1990er-Jahren bremste eine autoritär geführte Regierung den Reformweg. Das Land musste demokratische Standards zunächst aufholen." },
    en: { rel: "Slovakia joined in 2004 and adopted the euro in 2009. It is today seen as solidly integrated into the EU.",
      join: "Slovakia came into being in 1993 through the peaceful split of Czechoslovakia. In 2003 citizens voted to join.",
      diff: "In the 1990s an authoritarian-led government slowed the path of reform. The country first had to catch up on democratic standards." },
    ru: { rel: "Словакия вступила в 2004 году и ввела евро в 2009-м. Сегодня она считается прочно интегрированной в ЕС.",
      join: "Словакия возникла в 1993 году в результате мирного разделения Чехословакии. В 2003 году граждане проголосовали за вступление.",
      diff: "В 1990-е годы авторитарное правительство тормозило путь реформ. Стране пришлось сначала наверстать демократические стандарты." },
    zh: { rel: "斯洛伐克于2004年加入，并在2009年采用欧元。如今它被视为稳固地融入了欧盟。",
      join: "斯洛伐克于1993年因捷克斯洛伐克的和平分裂而诞生。2003年公民投票赞成加入。",
      diff: "1990年代，一个威权主导的政府拖慢了改革之路。该国首先必须在民主标准上迎头赶上。" } },

  IE: { year: 1973,
    de: { rel: "Irland trat 1973 bei und verwandelte sich später von einem armen Agrarland in eine moderne Wirtschaft. Als einziges englischsprachiges Land blieb es nach dem Brexit in der EU.",
      join: "Wegen der engen Verflechtung mit dem britischen Markt trat Irland zeitgleich mit Großbritannien bei. 1972 stimmten die Bürger klar dafür.",
      diff: "Bei mehreren Volksabstimmungen lehnten die Iren zunächst EU-Verträge ab (Nizza 2001, Lissabon 2008) und stimmten erst im zweiten Anlauf zu." },
    en: { rel: "Ireland joined in 1973 and later transformed from a poor agricultural country into a modern economy. As the only English-speaking country it remained in the EU after Brexit.",
      join: "Because of its close ties with the British market, Ireland joined at the same time as the United Kingdom. In 1972 citizens clearly voted in favour.",
      diff: "In several referendums the Irish at first rejected EU treaties (Nice 2001, Lisbon 2008) and only agreed on the second attempt." },
    ru: { rel: "Ирландия вступила в 1973 году и позже превратилась из бедной аграрной страны в современную экономику. Как единственная англоязычная страна она осталась в ЕС после Brexit.",
      join: "Из-за тесной связи с британским рынком Ирландия вступила одновременно с Великобританией. В 1972 году граждане чётко проголосовали за.",
      diff: "На нескольких референдумах ирландцы сначала отклоняли договоры ЕС (Ницца 2001, Лиссабон 2008) и соглашались лишь со второй попытки." },
    zh: { rel: "爱尔兰于1973年加入，后来从贫穷的农业国转变为现代经济体。作为唯一以英语为母语的国家，它在英国脱欧后仍留在欧盟。",
      join: "由于与英国市场联系紧密，爱尔兰与英国同时加入。1972年公民明确投票赞成。",
      diff: "在多次公投中，爱尔兰人起初否决了欧盟条约（2001年尼斯、2008年里斯本），直到第二次才同意。" } },

  HR: { year: 2013,
    de: { rel: "Kroatien ist mit dem Beitritt 2013 das bislang jüngste Mitglied der EU. Seine Küste macht es zu einem beliebten Reiseziel.",
      join: "Nach dem Zerfall Jugoslawiens und den Kriegen der 1990er-Jahre stellte Kroatien 2003 den Aufnahmeantrag.",
      diff: "Der Beitritt setzte die Zusammenarbeit mit dem UN-Kriegsverbrechertribunal voraus. Zudem musste ein Grenzstreit mit dem Nachbarn Slowenien beigelegt werden." },
    en: { rel: "Croatia is, with its 2013 accession, so far the youngest member of the EU. Its coastline makes it a popular travel destination.",
      join: "After the break-up of Yugoslavia and the wars of the 1990s, Croatia applied for membership in 2003.",
      diff: "Accession required cooperation with the UN war crimes tribunal. A border dispute with neighbouring Slovenia also had to be settled." },
    ru: { rel: "Хорватия со вступлением в 2013 году пока является самым молодым членом ЕС. Её побережье делает её популярным туристическим направлением.",
      join: "После распада Югославии и войн 1990-х годов Хорватия подала заявку на вступление в 2003 году.",
      diff: "Вступление требовало сотрудничества с трибуналом ООН по военным преступлениям. Кроме того, пришлось урегулировать пограничный спор с соседней Словенией." },
    zh: { rel: "克罗地亚于2013年加入，是迄今为止欧盟最年轻的成员国。其海岸线使它成为热门旅游目的地。",
      join: "在南斯拉夫解体和1990年代的战争之后，克罗地亚于2003年申请加入。",
      diff: "加入的前提是与联合国战争罪法庭合作。此外还必须解决与邻国斯洛文尼亚的边界争端。" } },

  LT: { year: 2004,
    de: { rel: "Litauen trat 2004 bei und führte 2015 den Euro ein. Es ist das südlichste der drei baltischen Länder.",
      join: "Litauen war 1990 die erste Sowjetrepublik, die ihre Unabhängigkeit erklärte. 2003 stimmten die Bürger deutlich für den EU-Beitritt.",
      diff: "Nach Jahrzehnten sowjetischer Herrschaft musste die Wirtschaft grundlegend umgebaut werden. Die Abhängigkeit von russischer Energie blieb lange eine Herausforderung." },
    en: { rel: "Lithuania joined in 2004 and adopted the euro in 2015. It is the southernmost of the three Baltic countries.",
      join: "In 1990 Lithuania was the first Soviet republic to declare independence. In 2003 citizens voted decisively to join the EU.",
      diff: "After decades of Soviet rule the economy had to be rebuilt from the ground up. Dependence on Russian energy remained a challenge for a long time." },
    ru: { rel: "Литва вступила в 2004 году и ввела евро в 2015-м. Это самая южная из трёх балтийских стран.",
      join: "В 1990 году Литва первой из советских республик провозгласила независимость. В 2003 году граждане уверенно проголосовали за вступление в ЕС.",
      diff: "После десятилетий советского правления экономику пришлось перестраивать заново. Зависимость от российских энергоносителей долго оставалась вызовом." },
    zh: { rel: "立陶宛于2004年加入，并在2015年采用欧元。它是三个波罗的海国家中最南端的一个。",
      join: "1990年，立陶宛是第一个宣布独立的苏联加盟共和国。2003年公民以明显多数投票赞成加入欧盟。",
      diff: "在数十年的苏联统治之后，经济必须从根本上重建。对俄罗斯能源的依赖长期是一项挑战。" } },

  SI: { year: 2004,
    de: { rel: "Slowenien trat 2004 bei und war das erste der neuen Mitglieder, das 2007 den Euro einführte. Es liegt zwischen den Alpen und der Adria.",
      join: "1991 erlangte Slowenien mit nur kurzem Konflikt seine Unabhängigkeit von Jugoslawien und wandte sich rasch der EU zu.",
      diff: "Ein langjähriger Grenzstreit mit dem Nachbarn Kroatien belastete die Beziehungen. Trotzdem galt Slowenien als wirtschaftlicher Musterschüler unter den neuen Mitgliedern." },
    en: { rel: "Slovenia joined in 2004 and was the first of the new members to adopt the euro, in 2007. It lies between the Alps and the Adriatic.",
      join: "In 1991 Slovenia gained independence from Yugoslavia after only a brief conflict and quickly turned to the EU.",
      diff: "A long-running border dispute with neighbouring Croatia strained relations. Even so, Slovenia was seen as an economic model pupil among the new members." },
    ru: { rel: "Словения вступила в 2004 году и первой из новых членов ввела евро — в 2007-м. Она расположена между Альпами и Адриатикой.",
      join: "В 1991 году Словения после лишь короткого конфликта обрела независимость от Югославии и быстро повернулась к ЕС.",
      diff: "Многолетний пограничный спор с соседней Хорватией осложнял отношения. Тем не менее Словения считалась экономическим отличником среди новых членов." },
    zh: { rel: "斯洛文尼亚于2004年加入，并在2007年率先在新成员中采用欧元。它位于阿尔卑斯山与亚得里亚海之间。",
      join: "1991年，斯洛文尼亚在仅短暂的冲突后从南斯拉夫获得独立，并迅速转向欧盟。",
      diff: "与邻国克罗地亚长期的边界争端使关系紧张。尽管如此，斯洛文尼亚被视为新成员中的经济模范。" } },

  LV: { year: 2004,
    de: { rel: "Lettland trat 2004 bei und führte 2014 den Euro ein. Die Hauptstadt Riga ist eine wichtige Ostsee-Metropole.",
      join: "Nach der Unabhängigkeit von der Sowjetunion 1991 orientierte sich Lettland nach Westen. 2003 stimmten die Bürger für den Beitritt.",
      diff: "Die Integration der großen russischsprachigen Minderheit war heikel. 2008 traf die Finanzkrise das Land hart und erforderte internationale Hilfe." },
    en: { rel: "Latvia joined in 2004 and adopted the euro in 2014. Its capital Riga is an important Baltic Sea metropolis.",
      join: "After independence from the Soviet Union in 1991, Latvia oriented itself towards the West. In 2003 citizens voted to join.",
      diff: "Integrating the large Russian-speaking minority was delicate. In 2008 the financial crisis hit the country hard and required international assistance." },
    ru: { rel: "Латвия вступила в 2004 году и ввела евро в 2014-м. Столица Рига — важный мегаполис на Балтике.",
      join: "После независимости от Советского Союза в 1991 году Латвия сориентировалась на Запад. В 2003 году граждане проголосовали за вступление.",
      diff: "Интеграция крупного русскоязычного меньшинства была деликатным вопросом. В 2008 году финансовый кризис сильно ударил по стране и потребовал международной помощи." },
    zh: { rel: "拉脱维亚于2004年加入，并在2014年采用欧元。首都里加是重要的波罗的海大都市。",
      join: "1991年从苏联独立后，拉脱维亚转向西方。2003年公民投票赞成加入。",
      diff: "融合庞大的俄语少数族群十分棘手。2008年金融危机重创该国，需要国际援助。" } },

  EE: { year: 2004,
    de: { rel: "Estland trat 2004 bei, führte 2011 den Euro ein und gilt heute als digitaler Vorreiter Europas. Vieles im Alltag läuft dort online.",
      join: "Nach der Unabhängigkeit von der Sowjetunion 1991 setzte Estland konsequent auf Reformen und Westbindung. 2003 stimmten die Bürger für den Beitritt.",
      diff: "Die Fragen rund um die russischsprachige Minderheit und die Staatsbürgerschaft waren lange schwierig. Das kleine Land musste seine Wirtschaft rasch modernisieren." },
    en: { rel: "Estonia joined in 2004, adopted the euro in 2011 and is today regarded as Europe's digital pioneer. Much of everyday life there runs online.",
      join: "After independence from the Soviet Union in 1991, Estonia pursued reforms and ties with the West consistently. In 2003 citizens voted to join.",
      diff: "Questions around the Russian-speaking minority and citizenship were difficult for a long time. The small country had to modernise its economy quickly." },
    ru: { rel: "Эстония вступила в 2004 году, ввела евро в 2011-м и сегодня считается цифровым первопроходцем Европы. Многое в повседневной жизни там происходит онлайн.",
      join: "После независимости от Советского Союза в 1991 году Эстония последовательно делала ставку на реформы и связь с Западом. В 2003 году граждане проголосовали за вступление.",
      diff: "Вопросы вокруг русскоязычного меньшинства и гражданства долго были непростыми. Маленькой стране пришлось быстро модернизировать экономику." },
    zh: { rel: "爱沙尼亚于2004年加入，2011年采用欧元，如今被视为欧洲的数字先锋。那里日常生活的许多事务都在线上进行。",
      join: "1991年从苏联独立后，爱沙尼亚坚定推进改革并与西方建立联系。2003年公民投票赞成加入。",
      diff: "围绕俄语少数族群和公民身份的问题长期存在困难。这个小国必须迅速实现经济现代化。" } },

  CY: { year: 2004,
    de: { rel: "Zypern trat 2004 bei und führte 2008 den Euro ein. Die Insel liegt im östlichen Mittelmeer nahe Asien.",
      join: "Als Inselstaat mit enger Verbindung zu Europa stellte Zypern früh den Aufnahmeantrag und wurde 2004 Mitglied.",
      diff: "Die Insel ist seit 1974 geteilt; im türkisch kontrollierten Norden gilt das EU-Recht nicht. 2013 geriet Zypern zudem in eine schwere Bankenkrise." },
    en: { rel: "Cyprus joined in 2004 and adopted the euro in 2008. The island lies in the eastern Mediterranean close to Asia.",
      join: "As an island state with close ties to Europe, Cyprus applied early and became a member in 2004.",
      diff: "The island has been divided since 1974; EU law does not apply in the Turkish-controlled north. In 2013 Cyprus also fell into a severe banking crisis." },
    ru: { rel: "Кипр вступил в 2004 году и ввёл евро в 2008-м. Остров расположен в восточном Средиземноморье, близко к Азии.",
      join: "Как островное государство с тесными связями с Европой Кипр рано подал заявку и стал членом в 2004 году.",
      diff: "Остров разделён с 1974 года; на контролируемом Турцией севере право ЕС не действует. В 2013 году Кипр к тому же попал в тяжёлый банковский кризис." },
    zh: { rel: "塞浦路斯于2004年加入，并在2008年采用欧元。该岛位于地中海东部，靠近亚洲。",
      join: "作为与欧洲联系密切的岛国，塞浦路斯很早就提出申请，并于2004年成为成员。",
      diff: "该岛自1974年起分裂；在土耳其控制的北部欧盟法律不适用。2013年塞浦路斯还陷入严重的银行危机。" } },

  LU: { year: 1958,
    de: { rel: "Luxemburg ist Gründungsmitglied und trotz seiner geringen Größe ein wichtiger EU-Standort. Hier haben unter anderem der Europäische Gerichtshof seinen Sitz.",
      join: "Gemeinsam mit Belgien und den Niederlanden bildete Luxemburg früh die Benelux-Union. 1957 gehörte es zu den sechs Gründern der EWG.",
      diff: "Als sehr kleines Land muss Luxemburg sein Gewicht klug einsetzen. Seine Rolle als Finanzplatz wird international immer wieder kritisch diskutiert." },
    en: { rel: "Luxembourg is a founding member and, despite its small size, an important EU location. It hosts the European Court of Justice, among others.",
      join: "Together with Belgium and the Netherlands, Luxembourg formed the Benelux union early on. In 1957 it was among the six founders of the EEC.",
      diff: "As a very small country Luxembourg must use its weight wisely. Its role as a financial centre is repeatedly discussed critically internationally." },
    ru: { rel: "Люксембург — страна-основатель и, несмотря на малые размеры, важный центр ЕС. Здесь, среди прочего, находится Суд Европейского союза.",
      join: "Вместе с Бельгией и Нидерландами Люксембург рано образовал союз Бенилюкс. В 1957 году он был среди шести основателей ЕЭС.",
      diff: "Как очень маленькая страна Люксембург должен разумно использовать свой вес. Его роль финансового центра на международном уровне регулярно обсуждается критически." },
    zh: { rel: "卢森堡是创始成员国，尽管面积很小，却是重要的欧盟所在地。欧洲法院等机构设在这里。",
      join: "卢森堡很早就与比利时、荷兰组成比荷卢联盟。1957年它是欧洲经济共同体六个创始国之一。",
      diff: "作为一个非常小的国家，卢森堡必须明智地运用自身影响力。它作为金融中心的角色在国际上不断受到批评性讨论。" } },

  MT: { year: 2004,
    de: { rel: "Malta trat 2004 bei und ist mit rund einer halben Million Einwohnern das kleinste EU-Land. 2008 führte es den Euro ein.",
      join: "Der Inselstaat im Mittelmeer stimmte 2003 in einer knappen Volksabstimmung für den Beitritt.",
      diff: "Als winziges Land muss Malta seine Interessen behaupten. Wegen seiner Lage steht es zudem im Mittelmeer stark unter dem Druck der Migration." },
    en: { rel: "Malta joined in 2004 and, with around half a million inhabitants, is the smallest EU country. In 2008 it adopted the euro.",
      join: "The Mediterranean island state voted to join in a narrow referendum in 2003.",
      diff: "As a tiny country Malta must assert its interests. Because of its location it is also under strong migration pressure in the Mediterranean." },
    ru: { rel: "Мальта вступила в 2004 году и с населением около полумиллиона человек является самой маленькой страной ЕС. В 2008 году она ввела евро.",
      join: "Островное государство в Средиземном море проголосовало за вступление на референдуме 2003 года с небольшим перевесом.",
      diff: "Как крошечная страна Мальта должна отстаивать свои интересы. Из-за своего расположения она к тому же испытывает сильное миграционное давление в Средиземноморье." },
    zh: { rel: "马耳他于2004年加入，约五十万人口使其成为最小的欧盟国家。2008年它采用了欧元。",
      join: "这个地中海岛国在2003年以微弱多数的公投中投票赞成加入。",
      diff: "作为一个极小的国家，马耳他必须维护自身利益。由于其地理位置，它在地中海还承受着巨大的移民压力。" } },
};
